spring:
  datasource:
    url: jdbc:h2:file:./data/prices
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

    com:
      baeldung:
        testloglevel: DEBUG
