
CREATE TABLE  IF NOT EXISTS PRICES
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID   INT,
    START_DATE DATE NOT NULL,
    END_DATE   DATE NOT NULL,
    PRICE_LIST DOUBLE PRECISION,
    PRODUCT_ID INT,
    PRIORITY   INT,
    PRICE      DOUBLE PRECISION,
    CURR       VARCHAR (5) DEFAULT NULL
);
