spring:
  datasource:
    url: jdbc:h2:file:./data/prices
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

flyway:
  enabled: true
  locations: migration
  url: jdbc:h2:file:./data/prices
  table: prices_schema_version
  baselineOnMigrate: true
