spring:
  datasource:
    url: jdbc:h2:file:./data/prices

  h2:
    console:
      enabled: true
      path: /h2

flyway:
  enabled: true
  locations: migration
  url: jdbc:h2:file:./data/prices
  table: prices_schema_version
  baselineOnMigrate: true
