spring:
  datasource:
    url: jdbc:h2:file:${DATABASE_FILE}
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
