
CREATE TABLE  IF NOT EXISTS PRICES
(
    BRAND_ID   LONG,
    START_DATE LONG NOT NULL,
    END_DATE   LONG NOT NULL,
    PRICE_LIST DOUBLE PRECISION,
    PRODUCT_ID LONG,
    PRIORITY   LONG,
    PRICE      DOUBLE PRECISION,
    CURR       VARCHAR (5) DEFAULT NULL,
    LAST_UPDATE LONG NOT NULL,
    PRIMARY KEY (BRAND_ID, START_DATE, END_DATE, PRODUCT_ID, CURR)
);
